### ISSUE TITLE
2.2.0: no test suite?

### ISSUE THREAD

**Issue by kloczek** [jaraco/jaraco.envs#2]
To be honest I'm a bit confused becau se I see tox.ini and pytest.ini files and pytest is not able to find any units and tox is failing.
tox.ini seems contails only release procedure.

FYI I'm trying to package your module as an rpm package. So I'm using the typical build, install and test cycle used on building packages from non-root account.
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

pytest output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-jaraco-envs-2.2.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-jaraco-envs-2.2.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
============================= test session starts ==============================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/jaraco.envs-2.2.0, configfile: pytest.ini
plugins: rerunfailures-9.1.1, cov-2.12.1, forked-1.3.0, xdist-2.3.0, flake8-1.0.7, shutil-1.7.0, virtualenv-1.7.0
collected 0 items

============================ no tests ran in 0.03s =============================
```

**Comment by jaraco** [comment]
jaraco.skeleton projects have a way of running tests even when there are no tests defined. It includes flake8 checks, black checks, mypy checks, and syntax checks (by way of doctest with no doctests present).

When I run the tests, I see 100% tests passing and 48% coverage:

```
$ tox
...
---------- coverage: platform darwin, python 3.10.1-final-0 ----------
Name             Stmts   Miss  Cover   Missing
----------------------------------------------
docs/conf.py         6      0   100%
jaraco/envs.py      50     29    42%   15, 18-20, 23-30, 33-36, 39-40, 43, 53-59, 71, 74-75
----------------------------------------------
TOTAL               56     29    48%


============================================================================== mypy ==============================================================================

Success: no issues found in 2 source files
======================================================================= 8 passed in 13.47s =======================================================================
____________________________________________________________________________ summary _____________________________________________________________________________
  python: commands succeeded
  congratulations :)
```

You need the `pytest-enabler` plugin if you want the plugin checks to be activated automatically. But even without those, I'd expect the `--doctest-modules` as indicated in pytest.ini to cause the source to be compiled and imported.

I probably could add some more tests too.

**Comment by jaraco** [comment]
#4 added some tests.
